export const auditActions = [
  "CUSTOMER_REGISTERED",
  "EMAIL_VERIFIED",
  "PASSWORD_CHANGED",
  "PASSWORD_RESET",
  "SESSIONS_REVOKED",
  "ADMIN_BOOTSTRAPPED",
  "ADMIN_MEMBERSHIP_CREATED",
  "ADMIN_MEMBERSHIP_DISABLED",
  "ADMIN_ROLE_ASSIGNED",
  "ADMIN_ROLE_REMOVED",
  "ADMIN_MFA_ENROLLED",
  "ADMIN_MFA_RESET",
  "ADMIN_RECOVERY_CODES_REGENERATED",
  "ADMIN_SENSITIVE_ACTION_DENIED",
] as const;

export type AuditAction = (typeof auditActions)[number];

export type AuditActorType = "CUSTOMER" | "ADMIN" | "GUEST" | "ANONYMOUS" | "SYSTEM";
